version: '3.5'

services:

  component-demoincdec:
    container_name: component-demoincdec
    build:
      context: ./
      dockerfile: component-demoincdec/Dockerfile
    volumes:
      - '/usr/src/app/node_modules'  
      - './component-demoincdec:/usr/src/app/'
    ports:
      - '3333:3333'      
    environment:
      - NODE_ENV=development  

  component-footer:
    container_name: component-footer
    build:
      context: ./
      dockerfile: component-footer/Dockerfile
    volumes:
      - '/usr/src/app/node_modules'  
      - './component-footer:/usr/src/app/'
    ports:
      - '3334:3333'      
    environment:
      - NODE_ENV=development    

  component-header:
    container_name: component-header
    build:
      context: ./
      dockerfile: component-header/Dockerfile
    volumes:
      - '/usr/src/app/node_modules'  
      - './component-header:/usr/src/app/'
    ports:
      - '3335:3333'      
    environment:
      - NODE_ENV=development            

  component-spa:
    container_name: component-spa
    build:
      context: ./
      dockerfile: component-spa/Dockerfile
    volumes:
      - ./component-spa:/usr/src/app/
      - '/usr/src/app/node_modules'      
      - ./component-demoincdec/dist:/usr/src/app/public/components/component-demoincdec     
      - ./component-footer/dist:/usr/src/app/public/components/component-footer  
      - ./component-header/dist:/usr/src/app/public/components/component-header        
    ports:
      - '9999:3000'
    environment:
      - NODE_ENV=development

  component-api:
    build:
      context: ./
      dockerfile: component-api/Dockerfile
    working_dir: /var/www
    volumes:
      - ./component-api:/var/www
    ports:
      - '9998:9000'
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  nginx:
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    working_dir: /var/www   
    ports:
      - 8080:80

        
volumes:
  dbdata:        