/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface ComponentHeader {
      'title': string;
    }
  }

  interface HTMLComponentHeaderElement extends StencilComponents.ComponentHeader, HTMLStencilElement {}

  var HTMLComponentHeaderElement: {
    prototype: HTMLComponentHeaderElement;
    new (): HTMLComponentHeaderElement;
  };
  interface HTMLElementTagNameMap {
    'component-header': HTMLComponentHeaderElement;
  }
  interface ElementTagNameMap {
    'component-header': HTMLComponentHeaderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'component-header': JSXElements.ComponentHeaderAttributes;
    }
  }
  namespace JSXElements {
    export interface ComponentHeaderAttributes extends HTMLAttributes {
      'onUserLoggedIn'?: (event: CustomEvent) => void;
      'title'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;